# Qual comando usamos para subir serviços de um compose file em segundo plano? E para encerrar tudo que foi criado através do compose file?
# Para subir em segundo plano, utiliza-se -d, de "daemon".
# Para encerrar tudo, utiliza-se down, desta forma: docker-compose -f nome-do-arquivo.yml down

version: "3"
services:

  web:
    image: php:7.4-apache  
    container_name: php
    ports:
      - "8080:80"
    volumes:
      - C:\Users\T-GAMER\projeto:/var/www/html/projeto

  banco:
    image: mysql:5.7.24
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - philips:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD:rootdb__

volumes:
  philips:
