CREATE TABLE professores
(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	nome VARCHAR(32) NOT NULL,
	sobrenome VARCHAR(32) NOT NULL,
	endereco VARCHAR(256) NOT NULL,
	telefone VARCHAR(11) NOT NULL,
	email VARCHAR(64) NOT NULL,
	data_nascimento DATE NOT NULL,
	nacionalidade VARCHAR(32) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE estudantes
(
	matricula NUMBER GENERATED BY DEFAULT AS IDENTITY,
	nome VARCHAR(32) NOT NULL,
	sobrenome VARCHAR(32) NOT NULL,
	email VARCHAR(64) NOT NULL,
	data_nascimento DATE NOT NULL,
	nacionalidade VARCHAR(32) NOT NULL,
	media_geral NUMBER DEFAULT 0 NOT NULL,
	PRIMARY KEY(matricula)
);

CREATE TABLE cursos
(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	nome VARCHAR(64) NOT NULL,
	ead CHAR(1) DEFAULT '1' NOT NULL,
	id_professor NUMBER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (id_professor) REFERENCES professores (id)
);

CREATE TABLE notas
(
	id_estudante NUMBER NOT NULL,
	id_curso NUMBER NOT NULL,
	nota_media NUMBER DEFAULT 0 NOT NULL,
	PRIMARY KEY (id_estudante, id_curso),
	FOREIGN KEY (id_estudante) REFERENCES estudantes (matricula),
	FOREIGN KEY (id_curso) REFERENCES cursos (id)
);