CREATE TABLE professores
(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	nome VARCHAR(32) NOT NULL,
	sobrenome VARCHAR(32) NOT NULL,
	endereco VARCHAR(256) NOT NULL,
	telefone VARCHAR(11) NOT NULL,
	email VARCHAR(64) NOT NULL,
	data_nascimento DATE NOT NULL,
	nacionalidade VARCHAR(32) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE estudantes
(
	matricula NUMBER GENERATED BY DEFAULT AS IDENTITY,
	nome VARCHAR(32) NOT NULL,
	sobrenome VARCHAR(32) NOT NULL,
	email VARCHAR(64) NOT NULL,
	data_nascimento DATE NOT NULL,
	nacionalidade VARCHAR(32) NOT NULL,
	media_geral NUMBER DEFAULT 0 NOT NULL,
	PRIMARY KEY(matricula)
);

CREATE TABLE cursos
(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	nome VARCHAR(64) NOT NULL,
	ead CHAR(1) DEFAULT '1' NOT NULL,
	max_estudantes NUMBER NOT NULL,
	id_professor NUMBER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (id_professor) REFERENCES professores (id)
);

CREATE TABLE notas
(
	id_estudante NUMBER NOT NULL,
	id_curso NUMBER NOT NULL,
	nota_media NUMBER DEFAULT 0 NOT NULL,
	PRIMARY KEY (id_estudante, id_curso),
	FOREIGN KEY (id_estudante) REFERENCES estudantes (matricula),
	FOREIGN KEY (id_curso) REFERENCES cursos (id)
);

INSERT INTO professores VALUES (1, 'Antonio', 'Oliveira', 'Rua A número 100, Abaeté, MG', '31912345678', 'antonio@email.com', TO_DATE('01/01/1991', 'DD/MM/YYYY'), 'brasileiro');

INSERT INTO professores VALUES (2, 'Bernardo', 'Oliveira', 'Rua B número 200, Belo Horizonte, MG', '31991234567', 'bernardo@email.com', TO_DATE('02/02/1992', 'DD/MM/YYYY'), 'brasileiro');

INSERT INTO professores VALUES (3, 'Caio', 'Oliveira', 'Rua C número 300, Campos do Jordão, SP', '12912345678', 'caio@email.com', TO_DATE('03/03/1993', 'DD/MM/YYYY'), 'brasileiro');

INSERT INTO estudantes VALUES (1, 'Antonio', 'Oliveira', 'antonio@email.com', TO_DATE('01/01/1991', 'DD/MM/YYYY'), 'brasileiro'), 0);

INSERT INTO estudantes VALUES (2, 'Bernardo', 'Oliveira', 'bernardo@email.com', TO_DATE('02/02/1992', 'DD/MM/YYYY'), 'brasileiro'), 0);

INSERT INTO estudantes VALUES (3, 'Caio', 'Oliveira', 'caio@email.com', TO_DATE('03/03/1993', 'DD/MM/YYYY'), 'brasileiro'), 0);

INSERT INTO cursos VALUES (1, 'PL/SQL', '1', 31, 1);

INSERT INTO cursos VALUES (2, 'Angular', '0', 100, 2);

INSERT INTO cursos VALUES (3, 'Spring', '1', 15, 3);

INSERT INTO notas VALUES (1, 2, 0);

INSERT INTO notas VALUES (1, 3, 0);

INSERT INTO notas VALUES (3, 2, 0);